### PR TITLE
Hover Message for Surfing Icon

### PR DESCRIPTION
**Pull request by akanex115**
## Issue
#75 

## Checklist

- [x] One of the followings is handled
　　・At least one or more issue is linked to this PR
　　・[The issue template](https://github.com/ajktown/.github/blob/main/issue_template.md) has been replaced to the [issue](https://github.com/ajktown/.github/blob/main/pull_request_template.md#issue) above, if no issue is related to this PR
- [x]  Assignee is set
- [x]  Labels are set
- [x]  yarn inspect is run
- [x] Operation Check is done
- [x]  TODOs of associated issue (or TODOs here, if present) are handled and

### CODE REVIEW

**Comment by mlajkim** [comment]
LGTM!
but can you update the comment with the format here:
https://github.com/ajktown/.github/blob/main/pull_request_template.md

example) 
https://github.com/ajktown/wordnote/pull/77

**Comment by akanex115** [comment]
Checklist
- [ ] One of the followings is handled
　　・At least one or more issue is linked to this PR
　　・[The issue template](https://github.com/ajktown/.github/blob/main/issue_template.md) has been replaced to the [issue](https://github.com/ajktown/.github/blob/main/pull_request_template.md#issue) above, if no issue is related to this PR
- [ ] Assignee is set
- [ ]  Labels are set
- [ ] yarn inspect is run
- [ ] Operation Check is done
- [ ] TODOs of associated issue (or TODOs here, if present) are handled and checked

checklistを追記しました。

**Comment by mlajkim** [comment]
image

こちらに直接入れてみてね

**Review by mlajkim — APPROVED** [review]
LGTM

**Pull request merged**
